# Generated by Django 3.1.7 on 2022-07-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Untitled', max_length=100)),
                ('price', models.FloatField(default=20.0)),
                ('description', models.TextField(default='No description')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
