# Generated by Django 3.1.7 on 2022-07-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20220721_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.TextField(blank=True),
        ),
    ]
