# Generated by Django 3.1.7 on 2022-07-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='classic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='trending',
            field=models.BooleanField(default=False),
        ),
    ]
