# Generated by Django 3.1.7 on 2022-07-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20220723_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='author',
            field=models.ManyToManyField(to='product.Author'),
        ),
    ]
