# Generated by Django 3.1.7 on 2022-07-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20220725_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='has_background',
            field=models.BooleanField(default=False),
        ),
    ]
